version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: auditchain-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahasia
      POSTGRES_DB: test_blockchain
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gateway-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    build: .
    container_name: auditchain-api
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-db
    volumes:
      - /home/besu/audit_blockchain/organizations:/home/besu/audit_blockchain/organizations:ro
    extra_hosts:
      - "peer0.org1.audit.example.com:100.125.142.44"
      - "peer0.org2.audit.example.com:100.126.175.124"
      - "peer0.org3.audit.example.com:100.103.85.7"
      - "orderer.audit.example.com:100.125.142.44"
    networks:
      - gateway-net
      - fabric-net

volumes:
  postgres-data:

networks:
  gateway-net:
    driver: bridge
  fabric-net:
    external: true
    name: fabric_test