// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@auditchain.local"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Autentikasi pengguna dan mendapatkan token JWT untuk akses API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Kredensial Login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login berhasil dan mengembalikan token",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Format request tidak valid",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Username atau Password salah!",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Akun dinonaktifkan karena client tidak aktif",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal mencetak token keamanan",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan informasi profil dari pengguna yang sedang login (berdasarkan JWT).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "Data profil user",
                        "schema": {
                            "$ref": "#/definitions/auth.ProfileResponseData"
                        }
                    },
                    "401": {
                        "description": "Token tidak memiliki identitas user yang valid",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Profil user tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui informasi profil pengguna yang sedang login. Bisa juga untuk mengubah password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Data Profil Baru",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ProfileUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profil berhasil diperbarui dan mengembalikan token baru jika password diubah",
                        "schema": {
                            "$ref": "#/definitions/auth.UpdateProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Validasi input gagal (misal username terlalu pendek)",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token tidak valid atau Password saat ini tidak sesuai",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Username sudah digunakan",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal memperbarui profil",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Mendaftarkan pengguna baru (auditor/admin) ke dalam perusahaan (client) tertentu.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Data Pendaftaran",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Pengguna berhasil didaftarkan",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Format tidak valid atau client_id belum diisi",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Perusahaan (Client ID) tidak terdaftar di sistem",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Username sudah digunakan",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal memproses pendaftaran",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/client": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil daftar semua klien/perusahaan yang terdaftar.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "List all clients",
                "responses": {
                    "200": {
                        "description": "Daftar klien",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Client"
                            }
                        }
                    },
                    "500": {
                        "description": "Gagal mengambil daftar klien",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendaftarkan klien/perusahaan baru dan mengembalikan API Key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Create a new client (SaaS tenant)",
                "parameters": [
                    {
                        "description": "Data Klien",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.CreateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Klien berhasil didaftarkan",
                        "schema": {
                            "$ref": "#/definitions/client.CreateClientResponse"
                        }
                    },
                    "400": {
                        "description": "Format tidak valid",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal mendaftarkan klien",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/client/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil detail informasi klien beserta konfigurasi agent dan kafka-nya.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Get client detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detail klien",
                        "schema": {
                            "$ref": "#/definitions/client.ClientDetailResponse"
                        }
                    },
                    "400": {
                        "description": "ID klien kosong",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Klien tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal mengambil data klien",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/inventory": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil inventaris/daftar resource unik (tabel/entity) yang terekam.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "Get resource inventory",
                "responses": {
                    "200": {
                        "description": "Daftar resource inventory",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/audit.ResourceInventoryItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Identitas client tidak valid",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal memuat daftar data",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil daftar log terbaru dengan dukungan paginasi dan filter.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "Get recent audit logs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Nomor Halaman (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Ukuran Halaman (default: 10)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter Status Integritas (valid, tampered, unreachable)",
                        "name": "integrity_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Urutan (asc, desc)",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter Tabel Sumber",
                        "name": "source_table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter Database Engine",
                        "name": "db_engine",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Waktu Mulai (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Waktu Selesai (RFC3339)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Daftar log beserta data paginasi",
                        "schema": {
                            "$ref": "#/definitions/audit.RecentLogsResponse"
                        }
                    },
                    "400": {
                        "description": "Parameter tidak valid",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Identitas client tidak valid",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal mengambil log terbaru",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil statistik ringkasan dashboard seperti jumlah log dan status integritas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "Get dashboard statistics",
                "responses": {
                    "200": {
                        "description": "Statistik dashboard",
                        "schema": {
                            "$ref": "#/definitions/audit.DashboardStatsResponse"
                        }
                    },
                    "401": {
                        "description": "Identitas client tidak valid",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal mengambil statistik",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/verify/{log_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memverifikasi integritas satu log tertentu (Lapis 2, 3, dan 4).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "Verify a specific log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Log",
                        "name": "log_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Verifikasi sukses dan log valid",
                        "schema": {
                            "$ref": "#/definitions/audit.VerifyLogResponse"
                        }
                    },
                    "202": {
                        "description": "Verifikasi pending/dalam proses",
                        "schema": {
                            "$ref": "#/definitions/audit.VerifyLogResponse"
                        }
                    },
                    "401": {
                        "description": "Identitas client tidak valid",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Log tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Verifikasi gagal/tampered pada suatu layer",
                        "schema": {
                            "$ref": "#/definitions/audit.VerifyLogResponse"
                        }
                    },
                    "500": {
                        "description": "Kesalahan sistem saat verifikasi",
                        "schema": {
                            "$ref": "#/definitions/audit.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audit.DashboardStatsResponse": {
            "type": "object",
            "properties": {
                "integrity_score": {
                    "type": "string",
                    "example": "99.79"
                },
                "pending_logs": {
                    "type": "integer",
                    "example": 37
                },
                "tampered_logs": {
                    "type": "integer",
                    "example": 3
                },
                "total_logs": {
                    "type": "integer",
                    "example": 1500
                },
                "total_resources": {
                    "type": "integer",
                    "example": 45
                },
                "unreachable_logs": {
                    "type": "integer",
                    "example": 10
                },
                "valid_logs": {
                    "type": "integer",
                    "example": 1450
                }
            }
        },
        "audit.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Pesan kesalahan atau validasi"
                }
            }
        },
        "audit.RecentLogsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Array of logs",
                    "type": "array",
                    "items": {}
                },
                "note": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "page": {
                            "type": "integer"
                        },
                        "page_size": {
                            "type": "integer"
                        },
                        "total_pages": {
                            "type": "integer"
                        },
                        "total_rows": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "audit.ResourceInventoryItem": {
            "type": "object",
            "properties": {
                "latest_log_id": {
                    "type": "string",
                    "example": "log-abc"
                },
                "resource": {
                    "type": "string",
                    "example": "orders"
                },
                "total_logs": {
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "audit.VerifyLogData": {
            "type": "object",
            "properties": {
                "actual_hash": {
                    "type": "string"
                },
                "agent_discrepancies": {},
                "agent_status": {
                    "type": "string"
                },
                "blockchain_tx_id": {
                    "type": "string"
                },
                "expected_hash": {
                    "type": "string"
                },
                "is_valid": {
                    "type": "boolean"
                },
                "log_id": {
                    "type": "string"
                },
                "merkle_root": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "audit.VerifyLogResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/audit.VerifyLogData"
                },
                "layer": {
                    "type": "string",
                    "example": "4_blockchain"
                },
                "log_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "auth.AuthRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "rahasia1234"
                },
                "username": {
                    "type": "string",
                    "example": "auditor_senior"
                }
            }
        },
        "auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.ProfileResponseData": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.ProfileUpdateRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "minLength": 4
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "client_id",
                "password",
                "username"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-1234-56789abcdef0"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "rahasia1234"
                },
                "username": {
                    "type": "string",
                    "example": "auditor_senior"
                }
            }
        },
        "auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.UserResponseData"
                }
            }
        },
        "auth.UpdateProfileResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.ProfileResponseData"
                }
            }
        },
        "auth.UserResponseData": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "client.ClientDetailResponse": {
            "type": "object",
            "properties": {
                "agent_config": {
                    "$ref": "#/definitions/models.AgentConfig"
                },
                "client": {
                    "$ref": "#/definitions/models.Client"
                },
                "kafka_config": {
                    "$ref": "#/definitions/models.ClientKafkaConfig"
                }
            }
        },
        "client.CreateClientRequest": {
            "type": "object",
            "required": [
                "company_name"
            ],
            "properties": {
                "action_field": {
                    "type": "string",
                    "example": "operasi"
                },
                "actor_field": {
                    "type": "string",
                    "example": "app_user"
                },
                "company_name": {
                    "type": "string",
                    "example": "PT Karya Bangsa"
                },
                "create_actor_field": {
                    "type": "string",
                    "example": "created_by"
                },
                "delete_actor_field": {
                    "type": "string",
                    "example": "deleted_by"
                },
                "fallback_actor_field": {
                    "type": "string",
                    "example": "db_user"
                },
                "resource_field": {
                    "type": "string",
                    "example": "tabel"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "update_actor_field": {
                    "type": "string",
                    "example": "updated_by"
                }
            }
        },
        "client.CreateClientResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "field_mapping": {
                    "type": "object",
                    "properties": {
                        "action_field": {
                            "type": "string"
                        },
                        "actor_field": {
                            "type": "string"
                        },
                        "create_actor_field": {
                            "type": "string"
                        },
                        "delete_actor_field": {
                            "type": "string"
                        },
                        "fallback_actor_field": {
                            "type": "string"
                        },
                        "resource_field": {
                            "type": "string"
                        },
                        "update_actor_field": {
                            "type": "string"
                        }
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Klien / Perusahaan SaaS berhasil didaftarkan"
                }
            }
        },
        "client.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Pesan kesalahan atau validasi"
                }
            }
        },
        "models.AgentConfig": {
            "type": "object",
            "properties": {
                "agent_url": {
                    "description": "URL Agent yang dapat dihubungi dari jaringan Gateway.\nContoh: http://192.168.11.50:9090",
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "connector_status": {
                    "description": "running, skipped, failed_xxx",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "db_engine": {
                    "description": "Informasi Database Klien (auto-filled dari install.sh telemetry)",
                    "type": "string"
                },
                "db_name": {
                    "description": "Nama database yang diaudit",
                    "type": "string"
                },
                "db_tables": {
                    "description": "Daftar tabel yang dimonitor (comma-separated)",
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "tailscale_ip": {
                    "description": "Field auto-filled oleh install.sh telemetry callback",
                    "type": "string"
                },
                "timeout_seconds": {
                    "description": "Timeout dalam detik untuk request ke Agent (default: 5)",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_column_name": {
                    "type": "string"
                },
                "user_sync_message": {
                    "description": "detail warning/error sync user table",
                    "type": "string"
                },
                "user_sync_status": {
                    "description": "ok, failed, skipped",
                    "type": "string"
                },
                "user_table_name": {
                    "description": "Deteksi Tabel User via CDC (Auto-filled dari install.sh telemetry)",
                    "type": "string"
                }
            }
        },
        "models.Client": {
            "type": "object",
            "properties": {
                "action_field": {
                    "type": "string"
                },
                "actor_field": {
                    "description": "Konfigurasi Mapping Field Dinamis\nDigunakan untuk memetakan field kustom klien ke field standar Gateway.\nContoh untuk klien yang menggunakan auditchain-agent (payload dari audit_trail):\n  ActorField           = \"app_user\"\n  FallbackActorField   = \"db_user\"   ← baru: fallback jika app_user null\n  ActionField          = \"operasi\"\n  ResourceField        = \"tabel\"",
                    "type": "string"
                },
                "api_key_prefix": {
                    "description": "Keamanan API Key",
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "create_actor_field": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "delete_actor_field": {
                    "type": "string"
                },
                "fallback_actor_field": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "resource_field": {
                    "type": "string"
                },
                "status": {
                    "description": "Konfigurasi SaaS",
                    "type": "string"
                },
                "update_actor_field": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ClientKafkaConfig": {
            "type": "object",
            "properties": {
                "actor_field": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "db_engine": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "kafka_brokers": {
                    "type": "string"
                },
                "pk_field": {
                    "type": "string"
                },
                "source_system": {
                    "type": "string"
                },
                "topic_prefix": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token dengan format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "AuditChain Gateway API",
	Description:      "API Enterprise untuk sistem audit log berbasis Blockchain dan Merkle Tree.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
